services:
  superhero.api:
    image: ${DOCKER_REGISTRY-}superheroapi
    build:
      context: .
      dockerfile: SuperHero.API/Dockerfile
    ports:
      - "7161:7161"
    environment:
      - ASPNETCORE_URLS=http://*:7161;
    depends_on: [superhero.database,superhero.log]
  superhero.mvc:
    image: ${DOCKER_REGISTRY-}superheromvc
    build:
      context: .
      dockerfile: SuperHero.MVC/Dockerfile
    ports:
      - "7000:7117"
    environment:
      - ASPNETCORE_URLS=http://*:7117
    depends_on:
      - superhero.api
  superhero.database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: superhero.database
    hostname: superhero.database
    ports:
      - "1401:1433"
    environment:
      - SA_PASSWORD=Password@1
      - ACCEPT_EULA=Y  
    restart: unless-stopped
  superhero.log:
    image: datalust/seq
    ports:
      - "5000:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    restart: unless-stopped
  

