---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-deployment
    namespace: superhero-namespace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
      - name: api-deployment
        image: kelarens/superhero-api:1.0.1
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__DefaultConnection
          value: Server=database-service,1434;Database=superherodb;Trusted_Connection=false;MultipleActiveResultSets=true;Encrypt=false;user id=sa;password=Password@1;
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: Serilog__WriteTo__1__Args__serverUrl
          value: http://seq-service
  selector:
    matchLabels:
      app: api-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: superhero-namespace
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32001
  selector:
    app: api-deployment
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: api-deployment-scaling
#   namespace: superhero-namespace
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: api-deployment
#   minReplicas: 1
#   maxReplicas: 10
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 50
#   - type: Resource
#     resource:
#       name: memory
#       target:
#         type: AverageValue
#         averageValue: 100Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-seed-job
  namespace: superhero-namespace
spec:
  template:
    spec:
      containers:
      - name: db-seed
        image: kelarens/superhero-db-seed:1.0.0
        env:
        - name: ConnectionStrings__DefaultConnection
          value: Server=database-service,1434;Database=superherodb;Trusted_Connection=false;MultipleActiveResultSets=true;Encrypt=false;user id=sa;password=Password@1;
        command: ["dotnet", "SuperHero.Seed.dll"]
      restartPolicy: Never
  backoffLimit: 1