// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHero.API.Data;

#nullable disable

namespace SuperHero.API.Migrations
{
    [DbContext(typeof(HeroContext))]
    [Migration("20250817104356_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperHero.API.Data.Hero", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Universe")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Image = "Supermanflying.png",
                            Level = 3,
                            Name = "SuperMan",
                            Universe = 1
                        },
                        new
                        {
                            Id = "2",
                            Image = "Wonder_Woman_(2017_film)_poster.jpg",
                            Level = 3,
                            Name = "WonderWoman",
                            Universe = 1
                        },
                        new
                        {
                            Id = "3",
                            Image = "Batman_Arkham_City_Game_Cover.jpg",
                            Level = 0,
                            Name = "Batman",
                            Universe = 1
                        },
                        new
                        {
                            Id = "4",
                            Image = "Web_of_Spider-Man_Vol_1_129-1.png",
                            Level = 1,
                            Name = "SpiderMan",
                            Universe = 0
                        },
                        new
                        {
                            Id = "5",
                            Image = "Hulk_(circa_2019).png",
                            Level = 2,
                            Name = "The Hulk",
                            Universe = 0
                        },
                        new
                        {
                            Id = "6",
                            Image = "Thor_(film)_poster.jpg",
                            Level = 4,
                            Name = "Thor",
                            Universe = 0
                        },
                        new
                        {
                            Id = "7",
                            Image = "Galactus_(2018).jpg",
                            Level = 4,
                            Name = "Galactus",
                            Universe = 1
                        },
                        new
                        {
                            Id = "8",
                            Image = "Iron_Man_(circa_2018).png",
                            Level = 1,
                            Name = "IronMan",
                            Universe = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
