// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHero.API.Data;

#nullable disable

namespace SuperHero.API.Migrations
{
    [DbContext(typeof(HeroContext))]
    [Migration("20250816151234_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperHero.API.Data.Hero", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Universe")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            Id = "6c25b85c-2245-4df8-bc14-6364984c4940",
                            Level = 3,
                            Name = "SuperMan",
                            Universe = 1
                        },
                        new
                        {
                            Id = "b4ad628e-4d50-4d22-9883-8d41169f34fa",
                            Level = 3,
                            Name = "WonderWoman",
                            Universe = 1
                        },
                        new
                        {
                            Id = "b271b120-7ed1-4edc-b905-e383f808365f",
                            Level = 0,
                            Name = "Batman",
                            Universe = 1
                        },
                        new
                        {
                            Id = "45de3945-7f14-4a9e-8861-330d6aae64c9",
                            Level = 1,
                            Name = "SpiderMan",
                            Universe = 0
                        },
                        new
                        {
                            Id = "302b7858-412f-4d31-8b95-9709d15620cc",
                            Level = 2,
                            Name = "The Hulk",
                            Universe = 0
                        },
                        new
                        {
                            Id = "21adcf68-c554-4896-93da-4070697350d0",
                            Level = 4,
                            Name = "Thor",
                            Universe = 0
                        },
                        new
                        {
                            Id = "2c62e566-406f-4fc0-b617-0e873fa81502",
                            Level = 4,
                            Name = "Galactus",
                            Universe = 1
                        },
                        new
                        {
                            Id = "22af5805-894a-4c4c-9154-80c71f82fdae",
                            Level = 1,
                            Name = "IronMan",
                            Universe = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
